feat: tests of the map style
WalTho/AthenaPWA pull request #21
Opened 2022-12-04 17:14 UTC by WalTho

Tests du style de Maps pour les serveurs 
*données en dur / quasi html pur / à refactorer avant de merge*

2022-12-04 17:17 UTC, XFGXTueur submitted a review, later dismissed

2023-01-11 17:42 UTC, WalTho commented
Comment variabiliser mes fonctions et states pour avoir un seul composant modal optimisé que j'aggrémente d'infos/image en fonction de la planète sur laquelle je clique ?

Cela me permettrait de sortir mon composant modal, avoir un code qui ne se répète pas et plus compréhensible

Aide bienvenue :)

2023-01-12 14:47 UTC, Gparquet requested changes

2023-01-12 14:47 UTC, Gparquet commented on src/Components/Maps/Maps.jsx
> +import React, { useState } from "react";
Le composant est trop gros. Le maximum de ligne pour un composant, ce sont à peu près 200 lignes. Généralement, ce n'est pas plus de 200, mais on n'est pas non plus à la ligne près.

Tout cela pour des soucis de relecture et de compréhension. Au plus, le composant est petit au mieux, c'est

2023-01-12 14:47 UTC, Gparquet commented on src/Components/Maps/Maps.jsx
> +    const [showAvernusModal, setShowAvernusModal] = useState(false);
Pourquoi tu ne gère pas un état qui contient un objet. La, tu as 20 useState qui contient des boolean. Tu pourrais avoir un objet qui contient tout par exemple : 

```
const [state, setState]= useState({
showTritonModal: false,
showOverventModal: false,
...
});
```

Imaginons que tu modifies uniquement la valeur showOverventModal tu peux faire par exemple : 

```
setState({
...state,
showOverventModal: true
});
```

2023-01-12 14:47 UTC, Gparquet commented on src/Components/Maps/Maps.jsx
> +        switch (name) {
ça tu peux le sortir dans une fonction à part dans un autre fichier même.

Il faut que tu sépares la logique métier (dans un container), de la vue (composant pure).

Tu peux te baser sur ce qui est fait à l'agence sur certain projet ;)

2023-03-12 15:15 UTC, WalTho commented on src/Components/Maps/Maps.jsx
> +        switch (name) {
Merci @Gparquet :) !!

J'ai refait à neuf la branche en partant d'avant qu' @aangee ne merge sur ma branche : https://github.com/WalTho/AthenaPWA/pull/48
:p 

ça pourrait être encore mieux mais c'est déjà ça

2023-03-12 15:15 UTC, closed without merging